#!/bin/bash

# 1. Recebendo argumentos
user=$1
masaaktif=$2

if [[ -z $user || -z $masaaktif ]]; then
    echo "Erro: Uso: addvless [usuario] [dias]"
    exit 1
fi

# 2. Verificação se o usuário já existe
CLIENT_EXISTS=$(grep -w "$user" /etc/xray/config.json | wc -l)
if [[ ${CLIENT_EXISTS} -ge 1 ]]; then
    echo "Erro: Usuário $user já existe no config.json"
    exit 1
fi

# 3. Configurações e IP
MYIP=$(curl -sS ipv4.icanhazip.com)
source /var/lib/crot/ipvps.conf 2>/dev/null
if [[ -z "$IP" ]]; then
    domain=$(cat /etc/xray/domain 2>/dev/null)
else
    domain=$IP
fi

tls="$(cat ~/log-install.txt | grep -w "Vless TLS" | cut -d: -f2|sed 's/ //g')"
nontls="$(cat ~/log-install.txt | grep -w "Vless None TLS" | cut -d: -f2|sed 's/ //g')"
uuid=$(cat /proc/sys/kernel/random/uuid)

hariini=$(date -d "0 days" +"%Y-%m-%d")
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")

# 4. Inserindo no config.json
sed -i '/#xray-vless-tls$/a\#### '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#xray-vless-nontls$/a\#### '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

# 5. Gerando Links Vless
xrayvless1="vless://${uuid}@${domain}:$tls?type=ws&encryption=none&security=tls&host=${domain}&path=/vless&allowInsecure=1&sni=${domain}#XRAY_VLESS_${user}"
xrayvless2="vless://${uuid}@${domain}:$nontls?type=ws&encryption=none&security=none&host=${domain}&path=/vless#XRAY_VLESS_${user}"

# 6. Reiniciando serviços
systemctl restart xray.service
service cron restart

# 7. Criando arquivo .txt para o cliente
mkdir -p /home/vps/public_html/
cat > /home/vps/public_html/vless-$user.txt <<-END
====================================================================
                       [Freedom Internet]
====================================================================
Remarks     : ${user}
IP/Host     : ${MYIP}
Address     : ${domain}
Port TLS    : $tls
Port No TLS : $nontls
User ID     : ${uuid}
Network     : ws
Created     : $hariini
Expired     : $exp
=========================
Link TLS    : ${xrayvless1}
=========================
Link No TLS : ${xrayvless2}
=========================
END

# 8. Saída curta para a API Node.js
echo "SUCESSO|$user|$uuid|$exp|$MYIP|$domain|$xrayvless1|$xrayvless2"
