# HTTPS - IP (self-signed)
server {
  listen       8445 ssl http2;
  server_name  82.165.182.12;
  root   /home/vps/public_html;

  ssl_certificate     /etc/xray/nginx-self.crt;
  ssl_certificate_key /etc/xray/nginx-self.key;
  ssl_protocols       TLSv1.2 TLSv1.3;
  ssl_ciphers         HIGH:!aNULL:!MD5;

  access_log /var/log/nginx/vps-ssl-access.log;
  error_log  /var/log/nginx/vps-ssl-error.log error;

  location = / {
    index index.html;
  }

  location ~* \.(ovpn|txt|zip|sh|conf)$ {
    types { }
    default_type application/octet-stream;
    add_header Content-Disposition 'attachment' always;
    add_header Cache-Control 'no-store' always;
  }

  location / {
    try_files $uri =404;
  }
}

# HTTPS - Dominio (Let\'s Encrypt)
server {
  listen       8445 ssl http2;
  server_name  de.checker.mobi *.de.checker.mobi;
  root   /home/vps/public_html;

  ssl_certificate     /etc/xray/xray-fullchain.crt;
  ssl_certificate_key /etc/xray/xray-le.key;
  ssl_protocols       TLSv1.2 TLSv1.3;
  ssl_ciphers         HIGH:!aNULL:!MD5;

  access_log /var/log/nginx/vps-ssl-access.log;
  error_log  /var/log/nginx/vps-ssl-error.log error;

  location = / {
    index index.html;
  }

  location ~* \.(ovpn|txt|zip|sh|conf)$ {
    types { }
    default_type application/octet-stream;
    add_header Content-Disposition 'attachment' always;
    add_header Cache-Control 'no-store' always;
  }

  location / {
    try_files $uri =404;
  }
}

# HTTP:89 -> HTTPS redirect
server {
  listen       89;
  server_name  _;
  return 301 https://\$host:8445\$request_uri;
}
