local 82.165.182.12
port 53
proto udp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh2048.pem
auth SHA256
cipher AES-128-GCM
data-ciphers AES-128-GCM:AES-256-GCM:CHACHA20-POLY1305
server 10.9.0.0 255.255.255.0
push "dhcp-option DNS 1.0.0.1"
push "dhcp-option DNS 1.1.1.1"
push "redirect-gateway def1"
keepalive 10 60
topology subnet
persist-key
persist-tun
tls-server
tls-version-min 1.2
remote-cert-tls client
fast-io
sndbuf 524288
rcvbuf 524288
status /var/log/openvpn-53.log
verb 3
explicit-exit-notify 1
