<?php
$services = [
    ["name" => "Hysteria2", "cmd" => "systemctl status hysteria-server --no-pager | grep -o 'Active:.*'", "port" => "7070 UDP"],
    ["name" => "udp2raw DNS", "cmd" => "systemctl status udp2raw --no-pager | grep -o 'Active:.*'", "port" => "5353 UDP"],
    ["name" => "OpenVPN UDP53", "cmd" => "systemctl status openvpn-server@server-udp53 --no-pager 2>/dev/null | grep -o 'Active:.*' || echo 'Active: inactive'", "port" => "53 UDP"],
    ["name" => "OpenVPN UDP", "cmd" => "systemctl status openvpn-server@server-udp --no-pager 2>/dev/null | grep -o 'Active:.*' || echo 'Active: inactive'", "port" => "2200 UDP"],
    ["name" => "OpenVPN TCP", "cmd" => "systemctl status openvpn-server@server-tcp --no-pager 2>/dev/null | grep -o 'Active:.*' || echo 'Active: inactive'", "port" => "1194 TCP"],
    ["name" => "DNSTT", "cmd" => "systemctl status dnstt-server --no-pager 2>/dev/null | grep -o 'Active:.*' || echo 'Active: inactive'", "port" => "5300 UDP"],
];
$ip = trim(shell_exec("curl -s ifconfig.me"));
?><!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Painel VPN Premium</title><style>* { margin:0; padding:0; box-sizing:border-box } body{ background:#0a0a0a; color:#fff; font-family:'Segoe UI',sans-serif; min-height:100vh } .header{ background:linear-gradient(135deg,#1a1a2e,#16213e); padding:30px; text-align:center; border-bottom:3px solid #0f3460 } .header h1{ font-size:2em; background:linear-gradient(90deg,#00d4ff,#7b2ff7); -webkit-background-clip:text; -webkit-text-fill-color:transparent } .header p { color:#8892b0; margin-top:5px } .container{ max-width:900px; margin:30px auto; padding:0 20px } .status-grid{ display:grid; grid-template-columns:repeat(auto-fit,minmax(250px,1fr)); gap:20px } .card{ background:#1a1a2e; border-radius:15px; padding:20px; border:1px solid #2a2a4a; transition:transform 0.2s } .card:hover{ transform:translateY(-3px) } .card h3{ color:#00d4ff; margin-bottom:10px } .card .port{ color:#7b2ff7; font-size:0.85em; margin-bottom:8px } .card .status{ padding:5px 12px; border-radius:20px; display:inline-block; font-size:0.85em } .online{ background:#0a3d0a; color:#00ff88 } .offline{ background:#3d0a0a; color:#ff4444 } .info-box{ background:#1a1a2e; border-radius:15px; padding:20px; margin-top:30px; border:1px solid #2a2a4a } .info-box h3{ color:#00d4ff; margin-bottom:10px } .info-box .cmd{ background:#0a0a0a; padding:10px; border-radius:8px; color:#00ff88; font-family:monospace; margin:5px 0; word-break:break-all }</style></head><body><div class="header"><h1>Painel VPN Premium</h1><p>Servidor: <?php echo $ip; ?></p></div><div class="container"><div class="status-grid"><?php foreach($services as $svc): $status = shell_exec($svc['cmd']); $isOnline = strpos($status, 'active (running)') !== false; $class = $isOnline ? 'online' : 'offline'; $text = $isOnline ? 'ONLINE' : 'OFFLINE'; ?><div class="card"><h3><?php echo $svc['name']; ?></h3><div class="port">Porta: <?php echo $svc['port']; ?></div><span class="status <?php echo $class; ?>"><?php echo $text; ?></span></div><?php endforeach; ?></div><div class="info-box"><h3>Comandos Rapidos</h3><p style="color:#8892b0; margin:10px 0;">SSH no servidor:</p><div class="cmd">ssh root@<?php echo $ip; ?></div><p style="color:#8892b0; margin:10px 0;">Menu de gestao:</p><div class="cmd">menu-hy2</div><p style="color:#8892b0; margin:10px 0;">Hysteria2 Link (porta 7070 direta):</p><div class="cmd" style="font-size:0.75em;">hysteria2://p2ALJcq402o2JIFjrZawPO8g1c1KEqPGy3MI56MKefY%3D@<?php echo $ip; ?>:7070?insecure=1&sni=google.com&upmbps=1000&downmbps=1000&socks5=1080&mport=8080#Hysteria2</div></div></div></body></html>
